[server]
headless = true

[theme]
primaryColor = "#4a90e2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"

[client]
initialSidebarState = "expanded"

[browser]
gatherUsageStats = false